In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('BTC-ETH-LTC 1MAY22 22MAY22 1min.csv')

In [3]:
from datetime import datetime,  timezone, date, time
df.head()
# df.CloseTime = [datetime.fromtimestamp(ts / 1000) for ts in df.CloseTime ]

,OpenTime,LTC-USD_Open,LTC-USD_High,LTC-USD_Low,LTC-USD_Close,LTC-USD_Volume,CloseTime,LTC-QuoteAssetVolume,LTC-NumberOfTrades,LTC-TBBASV,...,BTC-USD_Open,BTC-USD_High,BTC-USD_Low,BTC-USD_Close,BTC-USD_Volume,BTC-QuoteAssetVolume,BTC-NumberOfTrades,BTC-TBBASV,BTC-TBQAV,BTC-ignore
0,2022-05-01 05:30:00,95.9,95.9,95.7,95.9,824.175,2022-05-01 05:30:59.999,78922.2075,87.0,133.757,...,37630.80,37665.29,37612.43,37645.92,85.80484,3.229136e+06,1271.0,37.66777,1.417547e+06,0.0
1,2022-05-01 05:31:00,95.8,95.9,95.7,95.8,172.279,2022-05-01 05:31:59.999,16498.9458,34.0,74.522,...,37645.92,37645.93,37622.48,37642.29,28.27385,1.064073e+06,677.0,18.31689,6.893296e+05,0.0
2,2022-05-01 05:32:00,95.8,96.0,95.8,95.9,320.815,2022-05-01 05:32:59.999,30763.7021,61.0,172.950,...,37642.28,37684.71,37642.28,37672.10,70.97044,2.673472e+06,904.0,29.13056,1.097094e+06,0.0
3,2022-05-01 05:33:00,96.0,96.1,95.8,96.1,726.735,2022-05-01 05:33:59.999,69705.2515,115.0,417.836,...,37672.11,37738.97,37661.89,37737.08,81.17584,3.059013e+06,1168.0,54.89804,2.068797e+06,0.0
4,2022-05-01 05:34:00,96.0,96.1,96.0,96.1,669.649,2022-05-01 05:34:59.999,64288.6794,65.0,471.394,...,37737.09,37737.09,37700.74,37717.79,38.43930,1.449841e+06,1022.0,15.17617,5.723768e+05,0.0

In [4]:
df.tail()

,OpenTime,LTC-USD_Open,LTC-USD_High,LTC-USD_Low,LTC-USD_Close,LTC-USD_Volume,CloseTime,LTC-QuoteAssetVolume,LTC-NumberOfTrades,LTC-TBBASV,...,BTC-USD_Open,BTC-USD_High,BTC-USD_Low,BTC-USD_Close,BTC-USD_Volume,BTC-QuoteAssetVolume,BTC-NumberOfTrades,BTC-TBBASV,BTC-TBQAV,BTC-ignore
31204,2022-05-22 21:34:00,71.0,71.0,70.9,71.0,283.856,2022-05-22 21:34:59.999,20148.1873,29.0,61.421,...,29901.70,29901.70,29885.09,29888.96,15.33061,4.582964e+05,451.0,6.83366,204267.255570,0.0
31205,2022-05-22 21:35:00,71.0,71.0,70.8,70.9,256.642,2022-05-22 21:35:59.999,18193.5240,49.0,23.571,...,29888.97,29888.97,29866.51,29872.73,36.14274,1.079837e+06,782.0,11.22420,335292.422096,0.0
31206,2022-05-22 21:36:00,70.8,70.9,70.8,70.9,69.955,2022-05-22 21:36:59.999,4953.4232,16.0,6.092,...,29872.74,29872.74,29865.25,29870.99,9.02012,2.694289e+05,381.0,0.92994,27778.741537,0.0
31207,2022-05-22 21:37:00,70.8,70.9,70.8,70.9,49.051,2022-05-22 21:37:59.999,3475.0439,16.0,22.331,...,29871.00,29881.94,29870.99,29871.45,8.91903,2.664827e+05,441.0,3.51760,105089.069082,0.0
31208,2022-05-22 21:38:00,70.9,70.9,70.8,70.8,42.261,2022-05-22 21:38:59.999,2993.0839,20.0,10.051,...,29871.45,29871.45,29865.46,29865.46,4.63919,1.385614e+05,130.0,0.96562,28839.783541,0.0

In [5]:
# calculating moving average
def sma(data , window):
    return (data.rolling(window = window).mean())

# bollinger band strat
def bollinger_bands(data , sma , window ,nstd):
#     standard deviation 
    std = data.rolling(window = window).std()
    upper_band = sma + std * nstd
    lower_band = sma - std * nstd
    return upper_band , lower_band

In [6]:
symbols = ['BTC', 'ETH','LTC']
# list(sma(df['BTC-USD_Open'], 20))

In [7]:
nstd = 3

for symbol in symbols :
    df[f'{symbol}_sma'] = sma(df[f'{symbol}-USD_Open'], 20)
    df[f'{symbol}-upper_band'] , df[f'{symbol}-lower_band'] = bollinger_bands(df[f'{symbol}-USD_Open'] ,df[f'{symbol}_sma'], 20 ,nstd)

In [8]:
# df.head()

In [9]:
df.dropna(inplace = True)

In [10]:
df.head()

,OpenTime,LTC-USD_Open,LTC-USD_High,LTC-USD_Low,LTC-USD_Close,LTC-USD_Volume,CloseTime,LTC-QuoteAssetVolume,LTC-NumberOfTrades,LTC-TBBASV,...,BTC-ignore,BTC_sma,BTC-upper_band,BTC-lower_band,ETH_sma,ETH-upper_band,ETH-lower_band,LTC_sma,LTC-upper_band,LTC-lower_band
19,2022-05-01 05:49:00,95.9,96.0,95.8,95.9,309.850,2022-05-01 05:49:59.999,29719.6098,55.0,215.960,...,0.0,37699.832,37817.840265,37581.823735,2731.9585,2740.725010,2723.191990,95.975,96.280864,95.669136
20,2022-05-01 05:50:00,95.9,95.9,95.6,95.8,521.992,2022-05-01 05:50:59.999,49968.0698,102.0,253.312,...,0.0,37701.307,37812.609742,37590.004258,2732.1535,2740.163280,2724.143720,95.975,96.280864,95.669136
21,2022-05-01 05:51:00,95.8,95.8,95.6,95.7,93.015,2022-05-01 05:51:59.999,8901.9749,20.0,55.631,...,0.0,37702.511,37809.214833,37595.807167,2732.2330,2739.921501,2724.544499,95.975,96.280864,95.669136
22,2022-05-01 05:52:00,95.7,95.8,95.6,95.7,210.847,2022-05-01 05:52:59.999,20177.8200,33.0,161.097,...,0.0,37703.625,37805.299822,37601.950178,2732.3810,2739.378873,2725.383127,95.970,96.308573,95.631427
23,2022-05-01 05:53:00,95.7,95.7,95.6,95.7,268.121,2022-05-01 05:53:59.999,25658.1488,72.0,107.630,...,0.0,37703.019,37806.777038,37599.260962,2732.3625,2739.382546,2725.342454,95.955,96.337891,95.572109

In [11]:
# class TradingEnv :
#     def __init__(self , balance_amount , balance_unit, trading_fee_multiplier):
        
#         self.balance_amount = balance_amount
#         self.balance_unit = balance_unit
#         self.trading_fee_multiplier = trading_fee_multiplier
#         self.buys = []
#         self.sells = []
        
#     def buy(self, symbol , buy_price, time):
#         self.balance_amount = (self.balance_amount / buy_price) *self.trading_fee_multiplier
#         self.balance_unit = symbol 
#         self.buys.append([symbol, time , buy_price])
        
#     def sell(self, sell_price, time ):
#         self.balance_amount = self.balance_amount *sell_price * self.trading_fee_multiplier
#         self.sells.append([self.balance_unit, time , sell_price])
#         self.balance_unit = 'USDT'

In [12]:
class TradingEnv:
    def __init__(self, balance_amount, balance_unit, trading_fee_multiplier):
        self.balance_amount = balance_amount
        self.balance_unit = balance_unit
        self.buys = []
        self.sells = []
        self.trading_fee_multiplier = trading_fee_multiplier
        
    def buy(self, symbol, buy_price, time):
        self.balance_amount = (self.balance_amount / buy_price) * self.trading_fee_multiplier
        self.balance_unit = symbol
        self.buys.append([symbol, time, buy_price])
        
    def sell(self, sell_price, time):
        self.balance_amount = self.balance_amount * sell_price * self.trading_fee_multiplier
        self.sells.append( [self.balance_unit, time, sell_price] )
        self.balance_unit = 'USDT'

In [13]:
env = TradingEnv(balance_amount = 1000, balance_unit ='USDT', trading_fee_multiplier = 0.99925)

In [14]:
# df.columns

In [15]:
for i in range(len(df)):
    if env.balance_unit == 'USDT':
        for symbol in symbols:
            if df[f'{symbol}-USD_Low'].iloc[i] < df[f'{symbol}-lower_band'].iloc[i] : #buy signal
                env.buy(symbol, df[f'{symbol}-lower_band'].iloc[i], df['OpenTime'].iloc[i])
                break
                
    if env.balance_unit != 'USDT':
        if df[f'{env.balance_unit}-USD_High'].iloc[i] > df[f'{env.balance_unit}-upper_band'].iloc[i] : #sell signal
            env.sell(df[f'{env.balance_unit}-upper_band'].iloc[i], df['OpenTime'].iloc[i])

if env.balance_unit != 'USDT':
    env.sell(df[f'{env.balance_unit}-USD_Close'].iloc[-1], df['OpenTime'].iloc[-1])

In [16]:
print(f'num buys: {len(env.buys)}')
print(f'num sells: {len(env.sells)}')
print(f'ending balance: {env.balance_amount} {env.balance_unit}')

num buys: 316
num sells: 316
ending balance: 738.6141633126774 USDT

In [17]:
# pip install plot_utils

In [19]:
from plot_utils import plot_results

ImportError: cannot import name 'plot_results' from 'plot_utils' (C:\Users\Hemant\AppData\Roaming\Python\Python39\site-packages\plot_utils\__init__.py)

In [20]:
plot_results(df, 'LTC', env.buys, env.sells)

NameError: name 'plot_results' is not defined